# Experimenting with PyTorch

For using PyTorch you can either use your own Computer or [Google Colab](https://colab.research.google.com/).

You need to install the [PyTorch](https://pytorch.org/) package which comes with some extra dependencies.

Install the following packages for this notebook:
- **PyTorch**
- **torchvision**
- **tqdm**
- **matplotlib**

If your computer is equpped with a GPU you can also install the GPU version of PyTorch. Otherwise install the CPU version, which is smaller in size and enough for the tasks of this practical.

For using the GPU version you need to fullfill some prerequisites first, which are a little time consuming.
- Make sure that your graphics card is new enough to handle the PyTorch environment. This can be checked by searching for the compute capability of your GPU and the compute capability requirements from the PyTorch module
- Install the latest NVIDIA driver
- Install suitable CUDA version
- Install CudNN
- Install PyTorch after all previous successful steps


Using Google Colab should avoid installing the above mentioned prerequisites.

## PyTorch Operations

In [1]:
import torch
import torch.nn as nn
import numpy as np
from torchsummary import summary

# Tensors

# Initialize a 1d torch tensor of size (6, 1) and name it 'data'. Initialize the tensor as random normal distribution
# Code here
data = torch.randn(6,1)



# Convert the torch tensor to a numpy array and convert it back afterwards. Keep the variable naming and just override the variable every time

# Code here
data = np.array(data)
data = torch.tensor(data)

# Tensors have a shape, a data type and are executed on some device on your computer. Find the mentioned tensor attributes and print them.

# Code here

print("Shape:",data.shape)
print("Type:",type(data))
print("Device:",data.device)
# Slicing works the same as with numpy arrays. No need to learn a new syntax here :)
# Try some slicing methods (i. e. the slicing methods we discussed in the first practical)

# Code here

data[1,]
data[:-1]
data[0,:]
data[:,0]
data[0:0, 1:1]
###
# Arithmetic operations
###

# Perform a matrix multiplication with two random tensors of different shape. The value initialization is of your choice.

# Code here
m1 = torch.rand(6,2)
m2 = torch.rand(2,2)

res = m1 @ m2
print("Matrix multiplication:")
print(res)


# Perform the hadamard (element-wise) product with two random initialized tensors.

# Code here

x1 = torch.rand(2,2)
x2 = torch.rand(2,2)

mul = x1 * x2
print("Element-wise:")
print(mul)

# For more useful tensor operations, plese check out their website: https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

Shape: torch.Size([6, 1])
Type: <class 'torch.Tensor'>
Device: cpu
Matrix multiplication:
tensor([[0.8138, 0.8922],
        [0.8187, 0.7379],
        [0.4179, 0.7186],
        [0.4107, 0.9331],
        [0.1087, 0.6072],
        [0.8967, 1.2521]])
Element-wise:
tensor([[0.0349, 0.2273],
        [0.2391, 0.1545]])


## PyTorch Sequential and Layers

In [2]:
# We now build our first neural network layers and combine them into one model

# First lets define an example Linear layer.
# Initialize a Linear layer from PyTorch of dimension (in_features=16, out_features=32).

# Code here

linear_1 = nn.Linear(16, 32)



# Print the layer attributes and print the weight of the Linear layer
# Forward a fitting random initialized 2d tensor through the layer and print the result
# What is the shape of the passed (forwarded) random tensor?


# Code here
print("Attributes",linear_1)

print(linear_1.weight.shape)

ten2 = torch.randn(size = (3, 16))

output = linear_1(ten2)

print(output.shape)

# Why does it work to just call an initialized layer by initialized_layer(input)?
# Check the source code for the Linear Layer and its parent 'Module' class here: https://pytorch.org/docs/stable/_modules/torch/nn/modules/linear.html#Linear
# Explain in your own words why the forward function of the 'Linear' class is automatically called when passing an input through the layer, i. e. initialized_layer(input)
# Hint: Check out the class inheritance!


# Your explanation here

# Because of the call method


# Build a sequential model with some linear layers stacked after each other. The number of layers is your choice, but be careful because it could cost a lot of time
# to pass data through the sequential model afterwards. Start e. g. with three linear layers :)
# You are not restricted to linear layers. Experiment a little bit here!

# Code here
model = nn.Sequential(
    nn.Linear(784, 32),  # input layer (do not change the in_features size of this layer - we need it later)
    nn.ReLU(),
    nn.Linear(32, 32),
    nn.ReLU(),
    nn.Linear(32, 16),
    nn.ReLU(),
    nn.Linear(16, 10)  # you can change the in_features of this layer but let the out_features at size 10 here - we need it layer
)

# print(summary(model, (784,)))

Attributes Linear(in_features=16, out_features=32, bias=True)
torch.Size([32, 16])
torch.Size([3, 32])


## PyTorch Forward Pass

In [5]:
# We initialized our model in the previous section
# Lets now also use the model to pass data through it

# Use the following tensor and pass it through your model from above
# You have to 'reformat' the tensor first

# Code here

data = torch.randn(size=(5, 1, 28, 28))

data = data.reshape(5,-1)

# read the image 'mnist_9.jpg' from the downloaded folder with the 'torchvision' python package and pass it through the network
# How does the tensor of the image looks like? Which information is in the different dimensions?

# Code here

# use this in case you're using colab
from google.colab import drive
drive.mount('/content/drive')

from torchvision.io import read_image

# path = "/content/drive/My Drive/Colab Notebooks/mnist_9.jpg"


# im = read_image(path)
# print("Image shape: ", im.shape)

# image = im / 255

# image = image.reshape(-1)



# # visualize the image from above with matplotlib
# import matplotlib.pyplot as plt

# # Code here
# plt.imshow(im[0], cmap='gray')

# plt.show()




Mounted at /content/drive


## PyTorch Neural Network Example Implementation

In [64]:
# This is only the application of your defined model
# You can use the following method to train your model and check its accuracy. You can also use parts of the code below for the following practicals.
# Just execute this box and it uses the predefined model from the previous task to run a training procedure. The variable name of the model must be 'model' (or change it accordingly).
# ATTENTION: No worries if you don't understand the implementation. This is just for showing you how your defined model performs in terms of accuracy.
# We will discuss everything in this code in future practicals.

import torchvision
import torchvision.transforms as transforms
import tqdm

#transforms.Normalize((0.5), (0.5))
def load_mnist_data(root_path='./data', batch_size=4):
    transform = transforms.Compose(
        [transforms.ToTensor()]
    )

    trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=2)

    testset = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False, num_workers=2)

    return trainloader  , testloader



def train_model(model, batch_size: int = 1, epochs: int = 1):
    # we only consider the mnist train data for this example
    train_loader, _ = load_mnist_data()


    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


    for epoch in range(epochs):
        running_loss = 0.0
        running_accuracy = []
        for imgs, targets in tqdm.tqdm(train_loader, desc=f'Training iteration {epoch + 1}'):
            # print(imgs)
            # print(targets)
            # break
            imgs, targets = imgs.to(device=device), targets.to(device=device)
            # print("shape")
            # print(imgs.shape)
            # print(len(targets))

            # zero the parameter gradients
            optimizer.zero_grad()
            # print("Images", imgs.reshape(imgs.shape[0], -1)[0])
            # break
            # print("targets",targets)
            # forward + backward + optimize
            outputs = model(imgs.reshape(imgs.shape[0], -1))
            print(outputs)

            print(targets)


            loss = criterion(outputs, targets)

            loss.backward()
            optimizer.step()

            # print statistics
            running_loss += loss.item()

            # Calculate the Accuracy (how many of all samples are correctly classified?)
            max_outputs = torch.max(outputs, dim=1).indices
            print(max_outputs)
            break
            accuracy = (max_outputs.detach() == targets.detach()).to(dtype=torch.float32).mean()
            running_accuracy.append(accuracy)

        print(f'Epoch {epoch + 1} finished with loss: {running_loss / len(train_loader):.3f} and accuracy {torch.tensor(running_accuracy).mean():.3f}')


# Run the model training with the name of your model variable, in this case 'model'
# train_model(model=model, batch_size=1, epochs=1)

In [65]:
train_model(model=model, batch_size=1, epochs=1)

Training iteration 1:   0%|          | 0/15000 [00:00<?, ?it/s]

tensor([[ 1.6535e+00, -7.2395e+00, -5.8665e+00, -6.5546e+00, -9.6127e+00,
         -3.6934e+00, -4.4204e+00, -7.2624e+00, -2.7794e+00, -6.7190e+00],
        [-2.4738e+01, -1.2215e+01, -7.8116e+00, -6.5804e+00, -1.2327e+01,
         -1.6683e+01, -4.1781e+01, -2.7049e+00, -6.9118e+00, -9.3472e+00],
        [-1.9283e+01, -1.2257e+01, -1.1168e+01,  1.5925e+00, -1.3543e+01,
         -6.0359e+00, -1.9866e+01, -9.9116e+00, -6.5761e+00, -5.5937e+00],
        [-1.5246e+01, -9.9456e+00, -1.9473e-02, -1.0465e+01, -2.7515e+01,
         -1.2796e+01, -2.0881e+01, -8.8519e+00, -1.4797e+01, -2.8982e+01]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 7, 3, 2], device='cuda:0')
tensor([0, 7, 3, 2], device='cuda:0')
Epoch 1 finished with loss: 0.000 and accuracy nan


In [ ]:
https://github.com/mrdbourke/pytorch-deep-learning/blob/main/02_pytorch_classification.ipynb